export enum MongoDbConstantsProvider {
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',

  CLIENT_SCHEMA = 'CLIENT_SCHEMA',
  ORDER_SCHEMA = 'ORDER_SCHEMA',
  PRODUCT_SCHEMA = 'PRODUCT_SCHEMA',
  USER_SCHEMA = 'USER_SCHEMA',
}