export enum HttpErrorCodesConstants{
  INTERNAL_SERVER_ERROR = 0,
  UNAUTHORIZED = 1,
  FORBIDDEN = 2,
  BAD_REQUEST = 3,

  EMAIL_NOT_VALID = 10,
  USER_FOUND = 12,
  USER_NOT_FOUND = 13,

  INVALID_ORDER_STATUS = 20,
  INVALID_PAGINATION_PARAM = 15,
  INVALID_SEARCH_PARAM = 16,

  CLIENT_FOUND = 18,
  CLIENT_NOT_CREATED = 14,
  CLIENT_NOT_FOUND = 17,
  CLIENT_NOT_UPDATED = 19,
}
